---
name: TomcatOnNimble

kind: pipeline
type: docker

clone:
  disable: true

steps:
  - name: pull
    image: appleboy/drone-ssh
    settings:
      host: nimble.najjarza.de
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 54322
      timeout: 1m
      script:
        - echo 'Deploy Start'
        - echo 'Git pull origin master'
        - cd /home/dariush/SamanPR/
        - git pull origin master
        - docker-compose up -d
        - echo 'git pull finished' 
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success

  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      become_pass:
        from_secret: ansible_become_pass
    settings:
      host: nimble.najjarza.de
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 54322
      timeout: 1m
      envs: [become_pass, TEST]
      script:
        - echo 'Ansible play start'
        - cd /home/dariush/SamanPR/spr/playbooks/
        - ansible-playbook -i inventory playbook.yml --extra-vars "ansible_become_pass=$${become_pass}"
        - echo 'Ansible play finished'
        - echo "Deploy Finished"
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success

