---
name: TomcatOnNimble

kind: pipeline
type: docker

clone:
  disable: true

steps:
  - name: pull
    image: appleboy/drone-ssh
    environment:
      become_pass:
        from_secret: ansible_become_pass
      testsecret:
        from_secret: test
    settings:
      host: nimble.najjarza.de
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      envs: [become_pass, testsecret]
      port: 54322
      timeout: 1m
      script:
        - echo 'Deploy Start'
        - cd /home/dariush/SamanPR/
        - git pull origin master
        - docker-compose up -d
        - cd spr/playbooks/
        - ansible all -m ping
        - echo become_pass > /tmp/file
        - echo $become_pass >> /tmp/file
        - echo ${become_pass} >> /tmp/file
        - echo $${become_pass} >> /tmp/file
        - echo testsecret >> /tmp/file
        - echo $testsecret >> /tmp/file
        - echo ${testsecret} >> /tmp/file
        - echo $${testsecret} >> /tmp/file
        - cat /tmp/file
        - ansible-playbook -i inventory playbook.yml --extra-vars 'ansible_become_pass=${become}'
        - echo "Deploy Finished"
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success
