---
name: TomcatOnNimble

kind: pipeline
type: docker

clone:
  disable: true

steps:
  - name: pull
    image: appleboy/drone-ssh
    settings:
      host: nimble.najjarza.de
      secrets: [ssh_username, ssh_password]
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 54322
      timeout: 1m
      script:
        - echo 'Deploy Start'
        - pwd && whoami
        - cd /home/dariush/SamanPR/
        - git pull origin master
        - docker-compose up -d
        - cd spr/playbooks/
        - ansible-playbook -i inventory playbook.yml --extra-vars 'ansible_become_pass="ssh_password"'
        - echo "Deploy Finished"
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success
