---
name: TomcatOnNimble

kind: pipeline
type: docker

clone:
  disable: true

steps:
  - name: pull
    image: appleboy/drone-ssh
    settings:
      host: nimble.najjarza.de
      secrets: [ssh_username, ssh_password,ansible_become_pass]
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      environment:
        become_pass:
          from_secret: ansible_become_pass
      port: 54322
      timeout: 1m
      script:
        - echo 'Deploy Start'
        - cd /home/dariush/SamanPR/
        - git pull origin master
        - docker-compose up -d
        - cd spr/playbooks/
        - ansible all -m ping
        - ansible-playbook -i inventory playbook.yml --extra-vars "ansible_become_pass='become_pass'"
        - echo "Deploy Finished"
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success
