---
name: TomcatOnNimble

kind: pipeline
type: docker

clone:
  disable: true

steps:
  - name: pull
    image: appleboy/drone-ssh
    settings:
      host: nimble.najjarza.de
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 54322
      timeout: 1m
      script:
        - echo 'Deploy Start'
        - echo 'Git pull origin master'
        - cd /home/dariush/SamanPR/
        - git pull origin master
        - docker-compose up -d
        - echo 'git pull finished' 
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success

  - name: Deploy
    environment:
      become_pass:
        from_secret: ansible_become_pass
      TEST:
        from_secret: test
    settings:
      envs: [become_pass, testsecret]
      script:
        - echo 'Ansible play start'
        - cd /home/dariush/SamanPR/spr/playbooks/
        - ansible all -m ping
        - echo test >> /tmp/file
        - echo TEST >> /tmp/file
        - echo $test >> /tmp/file
        - echo $${test} >> /tmp/file
        - echo "$test" >> /tmp/file
        - echo "$${test}" >> /tmp/file
        - echo $TEST >> /tmp/file
        - echo $${TEST} >> /tmp/file
        - echo "$TEST" >> /tmp/file
        - echo "$${TEST}"
        - pwd
        - whoami
        - cat /tmp/file
        - ansible-playbook -i inventory playbook.yml --extra-vars 'ansible_become_pass=${become_pass}'
        - echo "Deploy Finished"
      when:
        branch: master
        event: [push] # step only triggers on push events
        status: success

